site_name: GPU 集群用户指南
site_description: GPU 集群使用教程
site_author: yliu7949
site_url: https://saids.hpc.gleamoe.com/
repo_name: &repository yliu7949/SAIKS-HPC-docs
repo_url: https://github.com/yliu7949/SAIKS-HPC-docs
copyright: Available under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>.

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - markdown.extensions.def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/man.md
        - includes/authors.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra:
  social:
    - icon: octicons/comment-discussion-16
      link: https://saids.ustc.edu.cn/
    - icon: octicons/mark-github-16
      link: https://github.com/yliu7949/SAIKS-HPC-docs
  analytics:
    provider: google
    property: G-EXFPCGX99L

extra_css:
  - css/extra.css

plugins:
  - search
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized
        - git-committers:
            repository: *repository
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - typeset

nav:
  - 首页: index.md
  - 前言: preface.md
  - 计算集群概况: cluster.md
  - 快速开始:
    - 账号申请: guideline/account.md
    - 集群登录与文件传输: guideline/login.md
    - 设置运行环境: guideline/module.md
    - 代码编译: guideline/compile.md
    - 作业提交: guideline/slurm.md
    - 常用软件: guideline/software.md
  - 常见问题: faq.md
  - 可视化平台: scow.md
